name: Playwright Automation

on:

  push:
    branches:
      - main

  pull_request:

  schedule:
    - cron: "0 14 * * *"

  workflow_dispatch:

jobs:

  ui-tests:

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install Playwright Browsers
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

      - name: Execute Tests
        run: mvn clean test

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: extent-test-output/

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: screenshots/

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Videos
          path: videos/

      - name: Upload Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Traces
          path: traces/

      - name: Upload HAR
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HAR
          path: har/

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Logs
          path: logs/